### ISSUE TITLE
Add (POST) new user

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#11]
**As a developer**
**I want** to manually add new users to the database
**to be able to** assign workouts to them specifically

## Description
As a developer, I want to be able to send a POST request with necessary user details to the backend, which upon successful submission, stores the new user in the database and allows me to subsequently assign workouts to them.

## Acceptance Criteria

- [x] Create a POST endpoint "/api/users" to add a new workout to the backend.

## Tasks

(for developers team)

- [x] Create a POST request to send workout data to the backend.
- [x] Implement Unit and Integration Test.
