### ISSUE TITLE
GET user by ID

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#14]
**As a developer**
**I want** to find users by their ids
**to be able to** assign workouts to them specifically

## Description
As a developer, I want to be able to send a GET request to find a user by the id in my database.

## Acceptance Criteria

- [x] Create a GET endpoint "/api/users/id" to find a user.

## Tasks

(for developers team)

- [x] Create a GET request to get user data from the backend.
- [ ] Implement Unit and Integration Test.
