### ISSUE TITLE
GET all workouts

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#2]
**As a User** 
**I want** to see all my workouts on the homepage when I open the app
**to be able to** easily keep track of my fitness routine.

## Description
Implement a feature on the homepage that allows users to retrieve and view a list of all their workouts from the backend.

## Acceptance Criteria

- [x] Create a GET "/api/workouts/userId" endpoint to fetch all workouts from the backend.
- [x] Display the list of all workouts on the starting page of the frontend.

## Tasks

(for developers team)

- [x] Create a User model with "id and name".
- [x] Create a Workout model with "id, user, workoutName, workoutDay, description and plan".
- [x] Create a WorkoutExercise model with "exerciseName, sets, reps, weight and break".
- [x] Create a "Header" component in the UI.
- [x] Create a "AllWorkouts" component in the UI.
- [x] Implement a GET request to retrieve all workouts from the backend.
- [x] Update the frontend to display the list of workouts.
- [x] Implement Unit and Integration Test.
- [x] Add some styling
