### ISSUE TITLE
GET workout By Id

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#3]
**As a User**
**I want** to be able to view detailed information about each of my workouts
**to be able to** understand and analyze my exercise sessions in depth

#### Description
Development of a separate details page for each workout, displayed upon clicking a button on a workout card in the list.

#### Acceptance Criteria

- [x] Create a GET "/api/workouts/details/{id}" endpoint to fetch the workout specified by the id.
- [x] Display all informations given from the backend on a extra Route for each workout "/workout/:id".
- [x] When clicking a button on a workout card in the list view or navigating directly via the url the details page should be shown.

#### Tasks

- [x] Create the "WorkoutDetails" page component.
- [x] Add a button to each workout card, which navigates to the details-page when clicked.
- [x] Create a GET (get by id) request to retrieve the workout data from the backend.
- [x] Implement Unit and Integration Test.
- [x] Add some styling
