### ISSUE TITLE
Add (POST) new workout

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#4]
**As a user**
**I want** to add new workouts to my list
**to be able to** keep track of all my fitness activities

## Description
Develop a separate page with a user-friendly interface for inputting workout details, including workout name, description, and day.

## Acceptance Criteria

- [x] Create a POST endpoint "/api/workouts" to add a new workout to the backend.
- [x] The Route "/workout/add" should display the AddWorkout page with a form to add a workout.
- [x] Ensure that the added workout appears in the database.

## Tasks

(for developers team)

- [x] Create a "Add workout" button in the UI.
- [x] Create a "AddWorkout" page component.
- [x] Implement a form to input workout details.
- [x] Create a POST request to send workout data to the backend.
- [x] Implement Unit and Integration Test.
- [x] Add some styling
