### ISSUE TITLE
Edit (PUT) workout

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#5]
**As a User**
**I want** to edit the details of my workouts
**to be able to** correct or update the information as needed

#### Description
Develop a dedicated editing page for each workout, incorporating features that allow users to modify details like workout name, description, or day.

#### Acceptance Criteria

- [x] A "Edit"-Button is displayed on the details-page for each-workout.
- [x] When the "Edit" button for a workout is clicked, the user gets redirected to "/workout/:id/edit".
- [x] On the Edit-Page an edit form for that workout should appear.
- [x] When submitting the form the workout information should be updated in the backend and the user should be redirected to the details page.
- [x] Create an PUT Endpoint "/api/workouts/edit/{id} to update the workout.

#### Tasks

- [x] Add an "Edit" button in the details page.
- [x] Create the "EditWorkout" page component.
- [x] Implement an edit form to modify workout details.
- [x] Create a PUT request to update workout details on the backend.
- [x] Display updated information in the frontend after saving changes.
- [x] Implement Unit and Integration Test.
- [x] Add some styling.
