### ISSUE TITLE
DELETE workout

### ISSUE THREAD

**Issue by AljoschaNy** [AljoschaNy/capstone-project-fiturae#6]
**As a User**
**I want** the option to delete workouts from my list
**to be able to** remove sessions that are no longer relevant or were added by mistake

#### Description
Implement a deletion feature for individual workouts, including a confirmation dialog to ensure user consent before permanent removal.

#### Acceptance Criteria

- [x] Create a DELETE Endpoint "/api/workouts/{id}" which deletes the workout specified by the id.
- [x] On the details-page of each workout should be a "delete" Button.
- [x] When clicking on the 'delete' button  the workout should be removed from the database.

#### Tasks

- [x] Add a "delete" button to the details-page.
- [x] Create a DELETE request to remove the workout from the backend.
- [x] Implement Unit and Integration Test.
